### ISSUE TITLE
Version Info for Installed Modules

### ISSUE THREAD

**Issue by Arrow768** [SourceMod-Store/WebPanel-Core#4]
## Intro

With the release of 2.0.0 the Store Plugin and all its Modules will be changed to semver.

This allows to automatically check the version of and suggest updates for the Store Plugin and its Modules.
## Initial Setup

The WebPanel presents the user with a compatible list of plugins.
This list is generated by querying a central github repo that contains a list of all public store plugins
The user then downloads the plugins he wants and uploads them to his servers
## Possible improvements:
- Automatically download the plugins and then upload them to the servers via ftp
- Automatically import the json for each selected plugin
- Generate a core.cfg for each server and offer it for download (or automatically push it to the server via ftp)

The updater queries for each module the specified url.
The WebPanel then presents a compatible version (according to semver)
The updates are then automatically applied to the server
## Todo
- [ ] _optional_ Generate DB Tables to store the current module versions
- [ ] Get the modules.json
- [ ] _optional_ Write the modules.json to the db
- [ ] Check if the modules are up2date
- [ ] Check if there are known issues
- [ ] Check if the installed module are compatible
- [ ] Check if the installed modules are up2date
- [ ] Show available modules that are compatible
- [ ] Show a download link to the latest version
